name: GitHub Actions CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: example earthly test
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - name: run tests
        run: earthly -P +all
